const state = {
  messages: [],
  sessionList: [],
  quickLaunchHistory: [],
  currentSession: null,
  currentBrowserIds: [],
  currentSoftwareProfileId: '',
  availableBrowserIds: [],
  availableSoftwareProfileIds: [],
  browserConnectionsInitialized: false,
  browserConnectionsSnapshot: '',
  browserConnectionsError: '',
  browserConnectionProfileById: {},
  browserConnectionsLoading: false,
  currentCardId: '',
  sharedAutomationCardId: '',
  automationCards: [],
  automationCardsLoading: false,
  automationCardsRefreshQueued: false,
  automationCardsQueuedPreferredId: '',
  automationCardsSnapshot: '',
  automationCardsError: '',
  browserSelectionExplicitlyDisabled: false,
  browserSelectionTouched: false,
  accountAuthenticated: false,
  vipActive: false,
  loading: false,
  stopping: false,
  activeRequestId: '',
  generatingTitle: false,
  quota: null,
  lastQuotaCost: null,
  mcpCallLimit: 100,
  mcpCallLimitDraft: '100',
  mcpCallLimitMin: 1,
  mcpCallLimitMax: 1000,
  mcpSettingsLoaded: false,
  mcpSettingsLoading: false,
  mcpSettingsSaving: false,
  mcpSettingsStatus: '',
  mcpSettingsStatusType: '',
  customApiHasKey: false,
  customApiSaving: false,
  aiInputComposing: false,
  aiInputCompositionBase: '',
  aiInputCompositionDraft: '',
  aiInputCompositionCancelled: false,
  accountSessionRefreshQueued: false,
  dynamicDataRefreshQueued: false,
  dynamicUiRefreshPending: false,
  historySaveChains: new Map(),
  historySaveLatestPayloads: new Map(),
};

const HISTORY_LS_PREFIX = 'ai-free.ai-chat-history.v1.';
const SEND_BUTTON_ICONS = {
  send: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m22 2-7 20-4-9-9-4Z"></path><path d="M22 2 11 13"></path></svg>',
  stop: '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="7" y="7" width="10" height="10" rx="2"></rect></svg>',
};
const el = (id) => document.getElementById(id);
